import Footer from "@/components/Footer";
import PortalHeader from "@/components/payment/PortalHeader";
import PaymentReceiptView from "@/components/payment/PaymentReceiptView";

export default async function PaymentReceiptPage({
    params,
}: {
    params: Promise<{ id: string }>;
}) {
    const { id } = await params;

    return (
        <main className="min-h-screen bg-white">
            <PortalHeader
                eyebrow="Receipt lookup"
                title="Your VK Group payment receipt"
                description="Review, print, and keep a clean copy of the receipt generated by the payment backend once your application payment is verified."
            />
            <PaymentReceiptView id={id} />
            <Footer />
        </main>
    );
}
